# Generated by Django 6.0.1 on 2026-03-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
